In [1]:
import numpy as np

base = 7500
cost2 = 25000
cost3 = 75000

multipliers = [
    [24, 70, 41, 21, 60],
    [47, 82, 87, 80, 35],
    [73, 89, 100, 90, 17],
    [77, 83, 85, 79, 55],
    [12, 27, 52, 15, 30]
]

hunters = [
    [2, 4, 3, 2, 4],
    [3, 5, 5, 5, 3],
    [4, 5, 8, 7, 2],
    [5, 5, 5, 5, 4],
    [2, 3, 4, 2, 3]
]

In [3]:
m = np.array(multipliers)
h = np.array(hunters)

n = m/h*7500
n

array([[ 90000.        , 131250.        , 102500.        ,
         78750.        , 112500.        ],
       [117500.        , 123000.        , 130500.        ,
        120000.        ,  87500.        ],
       [136875.        , 133500.        ,  93750.        ,
         96428.57142857,  63750.        ],
       [115500.        , 124500.        , 127500.        ,
        118500.        , 103125.        ],
       [ 45000.        ,  67500.        ,  97500.        ,
         56250.        ,  75000.        ]])

In [4]:
basis_pcts = np.random.rand(5, 5)
basis_pcts /= basis_pcts.sum()
basis_pcts

array([[0.01352142, 0.08568094, 0.05396298, 0.04760939, 0.08576698],
       [0.04605063, 0.01017002, 0.00514421, 0.00094563, 0.05441222],
       [0.02923959, 0.01403158, 0.01017458, 0.01964093, 0.04458477],
       [0.06782672, 0.05348164, 0.03566316, 0.05765842, 0.05261312],
       [0.01246728, 0.07439307, 0.00503699, 0.06373837, 0.05618533]])

In [5]:
basis_pcts.sum()

1.0000000000000002

In [7]:
m/(h+100*basis_pcts)*7500

array([[ 53697.00487295,  41772.44263   ,  36623.28267325,
         23295.58008681,  35780.4558318 ],
       [ 46350.69822135, 102210.37206145, 118326.10206078,
        117772.61905758,  31097.39280727],
       [ 79073.25902789, 104245.43805054,  83171.99569956,
         75300.42674157,  19741.49546769],
       [ 49012.65012303,  60155.59966753,  74419.38454699,
         55035.17464007,  44540.12520709],
       [ 27720.21334029,  19397.83948501,  86595.4792221 ,
         13434.70141578,  26106.53226084]])

In [13]:
from tqdm import tqdm

res = np.zeros_like(m).astype(np.float32)
for _ in tqdm(range(1000000)):
    cur_probs = np.random.rand(5,5)
    cur_probs /= cur_probs.sum()
    res += m/(h+100*cur_probs)*7500
res /= 1000000
res

100%|█████████████████████████████████████████████████████████████████████| 1000000/1000000 [00:45<00:00, 21780.72it/s]


array([[36108.883, 71992.164, 49810.664, 31585.602, 61720.31 ],
       [57098.188, 73352.5  , 77822.82 , 71627.62 , 42541.434],
       [75110.33 , 79687.66 , 64950.7  , 64263.07 , 25561.229],
       [68904.6  , 74274.914, 76069.586, 70672.58 , 56565.836],
       [18050.13 , 32834.8  , 53460.168, 22561.695, 36479.58 ]],
      dtype=float32)

In [11]:
equalprobs = np.array([[1/25]*5]*5)
equalprobs

array([[0.04, 0.04, 0.04, 0.04, 0.04],
       [0.04, 0.04, 0.04, 0.04, 0.04],
       [0.04, 0.04, 0.04, 0.04, 0.04],
       [0.04, 0.04, 0.04, 0.04, 0.04],
       [0.04, 0.04, 0.04, 0.04, 0.04]])

In [12]:
m/(h+equalprobs*100)*7500

array([[30000.        , 65625.        , 43928.57142857, 26250.        ,
        56250.        ],
       [50357.14285714, 68333.33333333, 72500.        , 66666.66666667,
        37500.        ],
       [68437.5       , 74166.66666667, 62500.        , 61363.63636364,
        21250.        ],
       [64166.66666667, 69166.66666667, 70833.33333333, 65833.33333333,
        51562.5       ],
       [15000.        , 28928.57142857, 48750.        , 18750.        ,
        32142.85714286]])